#!/usr/bin/env bash
set -ex

if [ -z "$CI" ]; then
  ./script/prepare-env
fi

REACT_APP_BUILD_VERSION="$(date +%s)" \
REACT_APP_TRANSMISSION_API_URL=/transmission/rpc \
  ./node_modules/.bin/react-scripts build --base /transmission/web/
