#!/usr/bin/env bash
set -ex

if [ -z "$CI" ]; then
  ./script/prepare-env
fi

if [ "$BUILD_FOR_NPX_SERVE" != "1" ]; then
  export NEXT_PUBLIC_BASE_PATH=/transmission/web
  export NEXT_PUBLIC_TRANSMISSION_RPC_PATH=/transmission/rpc
fi

rm -rf out/ pwa-out/

./node_modules/.bin/next build
./node_modules/.bin/next export
cp -a pwa-out/* out/
