#!/usr/bin/env bash

main() {
  if [ -z "$1" ]; then
    usage

    exit 1
  fi

  PROXY_CONFIG="$(proxy-config)"
  TEMP_CONFIG_PATH="$(mktemp "${HOME}/.cors-proxy.XXXXX")"

  echo "${PROXY_CONFIG//__PROXY_URL__/$1}" > "${TEMP_CONFIG_PATH}"
  docker run \
    --rm \
    --publish 8080:80 \
    --volume "${TEMP_CONFIG_PATH}:/etc/nginx/conf.d/default.conf" \
    nginx

}

proxy-config() {
  echo '
server {
  listen 80 default_server;
  server_name localhost;

  set $allow_origin "*";
  set $allow_methods "GET, POST, PUT, DELETE, OPTIONS";
  set $allow_headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,X-Transmission-Session-Id,Authorization";
  set $expose_headers "Content-Length,Content-Range,X-Transmission-Session-Id";


  location / {
    if ($request_method = OPTIONS) {
      add_header "Access-Control-Allow-Origin" $allow_origin;
      add_header "Access-Control-Allow-Methods" $allow_methods;
      add_header "Access-Control-Allow-Headers" $allow_headers;
      add_header "Access-Control-Expose-Headers" $expose_headers;

      #
      # Tell client that this pre-flight info is valid for 20 days
      #
      add_header "Access-Control-Max-Age" 1728000;
      add_header "Content-Type" "text/plain; charset=utf-8";
      add_header "Content-Length" 0;
      return 204;
    }

    proxy_redirect off;
    proxy_set_header host $host;
    proxy_set_header X-real-ip $remote_addr;
    proxy_set_header X-forward-for $proxy_add_x_forwarded_for;

    proxy_pass __PROXY_URL__;
  }
}
  '
}

usage() {
  echo "Usage: $0 https://example.com:9091/transmission/rpc"
}

main "$@"
