#!/usr/bin/env bash
set -ex

find build/ -iname '*.map' -print -exec rm {} \;

mv build/ transmission-material-ui/
rm -f transmission-material-ui.zip
zip -r transmission-material-ui.zip transmission-material-ui/

RELEASE_TAG="release-$(date "+%F-%H-%M")"

gh release create "$RELEASE_TAG" --generate-notes --target "$GITHUB_SHA"
gh release upload "$RELEASE_TAG" transmission-material-ui.zip
