#!/usr/bin/env bash
set -ex

if [ -n "$NEXT_PUBLIC_TRANSMISSION_RPC_PROXY" ]; then
  ./script/create-proxy "${NEXT_PUBLIC_TRANSMISSION_RPC_PROXY}" &
fi

if [ -z "$CI" ]; then
  ./script/prepare-env
fi

exec ./node_modules/.bin/next dev
