#!/usr/bin/env bash
set -ex

if [ -z "$CI" ]; then
  ./script/prepare-env
fi

exec ./node_modules/.bin/react-scripts \
  --inspect=9243 \
  test \
  --env=jsdom \
  --runInBand \
  --clearMocks \
  --resetMocks \
  --verbose \
  "$@"
