#!/usr/bin/env bash
set -ex

./script/prepare-env
exec ./node_modules/.bin/react-scripts-ts \
  --inspect=9243 \
  test \
  --env=jsdom \
  --runInBand \
  --clearMocks \
  --resetMocks \
  --verbose \
  "$@"
