name: CI

on: [push]

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare-env
      run: ./script/prepare-env
    - name: Cache workspace
      uses: actions/upload-artifact@v1
      with:
        name: workspace-cache
        path: .

  build:
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
    - name: Download workspace cache
      uses: actions/download-artifact@v1
      with:
        name: workspace-cache
    - name: build
      run: ./script/build
      
  test:
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
    - name: Download workspace cache
      uses: actions/download-artifact@v1
      with:
        name: workspace-cache
    - name: test
      run: ./script/test
