name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - run: ./script/prepare-env
      - run: ./script/build
      - run: ./script/test
      - run: ./script/deploy
        if: endsWith(github.ref, '/master')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
