name: CI

on: [push]

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: prepare-env
      run: ./script/prepare-env
    - name: Compresss workspace
      run: |
        rm -f workspace-cache.tar.gz
        tar --exclude=workspace-cache.tar.gz czf workspace-cache.tar.gz .
    - name: Cache workspace
      uses: actions/upload-artifact@v1
      with:
        name: workspace-cache
        path: workspace-cache.tar.gz

  build:
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
    - name: Download workspace cache
      uses: actions/download-artifact@v1
      with:
        name: workspace-cache
    - name: Extract cache
      run: tar zxf workspace-cache.tar.gz
    - name: build
      run: ./script/build
      
  test:
    needs: prepare-env
    runs-on: ubuntu-latest
    steps:
    - name: Download workspace cache
      uses: actions/download-artifact@v1
      with:
        name: workspace-cache
    - name: Extract cache
      run: tar zxf workspace-cache.tar.gz
    - name: test
      run: ./script/test
